name: Build Node 18.8
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_call:
jobs:
  Build Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.8.0
      - name: Install backend dependencies
        run: |
          cd ./backend
          npm install
