name: Prepare cache
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    branches:
      - main
jobs:
  Cahce-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.8.0
      - name: Cache backend node modules
        id: cache-backend-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-backend-node-modules
        with:
          path: ${{ github.workspace }}/backend/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/backend/package-lock.json') }}
      - name: Install backend dependencies
        run: |
          cd ./backend
          npm install
  Cahce-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.8.0
      - name: Cache frontend node modules
        id: cache-frontend-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-frontend-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ${{ github.workspace }}/v-gift/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/v-gift/package-lock.json') }}
      - name: Install frontend dependencies
        run: |
          cd ./v-gift
          npm install
