name: Quality gate
run-name: ${{ github.actor }} runs linters 🚀
on:
  pull_request:
    branches:
      - main
jobs:
  Lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/prepare-frontend
      - name: Run frontend linter
        run: |
          cd ./v-gift
          npm run lint
