name: Tests
run-name: ${{ github.actor }} runs tests 🚀
on:
  pull_request:
    branches:
      - main
jobs:
  Tests-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: ./.github/actions/prepare-backend
      - name: Run backend tests
        run: |
          cd ./backend
          export APP_ENV=test
          npm run test
