name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    branches:
      - main
jobs:
  Tests-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.8.0
      - name: Cache node modules
        id: cache-backend-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-frontend-backend-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ./backend/node-modules
          key: ${{ runner.os }}-backend-${{ env.cache-name }}-${{ hashFiles('**/backend/package-lock.json') }}
      - name: Install backend dependencies
        if: ${{ steps.cache-backend-node-modules.outputs.cache-hit != 'true' }}
        run: |
          cd ./backend
          npm install
      - name: Run backend tests
        run: |
          cd ./backend
          export APP_ENV=test
          npm run test
